### PR TITLE
Ignore deprecated warnings and support safe_mode

### PR DESCRIPTION
**Pull request by beck**

### CODE REVIEW

**Comment by stefanor** [comment]
Where's the description? Why is this forked? What's the plan for upstreaming these changes to get off the fork again?

**Comment by beck** [comment]
> Where's the description?

I was hoping the title, linking tickets, and comments was enough.  Alas.

As a followup to the the Definitions class pull, I told @bearnard I'd update the tests to also test in safe_mode. This is problematic because when the tests are run in isolation the deprecated warning causes tests to fail (https://github.com/sebastianbergmann/phpunit/issues/1710).

This pull updates how phpunit opens a subprocess to ensure deprecated warnings are suppressed and that the subprocesses uses the same open_base dir and safe_mode settings.

> Why is this forked? 

Because I thought this was the easiest way to review changes.

> What's the plan for upstreaming these changes to get off the fork again?

None.

After reading through phpunit tickets, their sentiment is: "supporting legacy is a lot of work for few benefits.... I'm not going to do it but if you can get it done nice and clean I don't mind having it". Which is a contradiction because supporting legacy is rarely "nice and clean".

And he's right, trying to get safe_mode working has been grossly time consuming. I have no interest in pouring more time into trying to make this "nice and clean" (which I doubt is even possible).

If a long-lived fork is not acceptable, another approach I considered:

Since this <10 lines of code, store a patch next to the text script and after phpunit is composer installed, apply these changes.

**Comment by stefanor** [comment]
Ah, so these are workarounds to bugs.

:+1: Yeah, carrying a patch like that sounds like an option. You could probably try this PR as-is, upstream, and see what they say. It seems vaguely reasonable.

**Comment by beck** [comment]
This pull feels very specific to yola, instead of trying to get it pushed upstream, closing in favor of using a patch.

**Pull request closed without merging**
